### ISSUE TITLE
not responsive  (don't shows map on smartphones and tablets portrait)

### ISSUE THREAD

**Issue by jojo12** [admiralsmaster/osm_akuechler#2]
It's a pity, that the map is grey, when there is a small tablet or a smartphone.
Works best on desktops and tablets landscape

**Comment by akuechl** [comment]
I check it with my smartphone. I see no grey map.
Can you describe the used things in more detail: which smartphone, operating system, operating system version, browser...?

Thank you for your feedback.

**Comment by jojo12** [comment]
yes, I've seen your demo is responsive.
I inserted and adapted your demo and adapted it for my region. It's in a joomla 3.8 article on php 7.1.8
with protostar template. My example you can find intra.folk-tanz.ch on homepage. on desk all is ok, when I make the window smaller, the map goes away.

**Comment by akuechl** [comment]
OK, I checked your example. The reason is a CSS rule from your template which overwrite all image rules with "!important":

```css
/* FILE: /templates/purity_iii/css/template.css */
@media screen and (max-width: 992px) {
	article img, .article-intro img, 
	... (many other images rules) {
    		width: 100% !important;
	}
}
```

~~You can add following rule  to fix it:~~
~~.leaflet-tile.leaflet-tile-loaded {
    width: 128px !important;
}~~
~~I am still thinking about adding this rule to the plugin CSS. I'm not sure yet whether it's a good idea or not.~~

**Update**: Set the image size to 128px is a bad idea. The tiles image size is 256px, with activated retina detection the images will be shrink to 128px on retina displays.

By the way, you can set the loading of tiles (card images) to HTTPS by setting the Tiles URL in the plugin settings to `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`.
